<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opt_lohi</name>
   <tag></tag>
   <elementGuidId>fe9c0af0-7f79-4fde-a58c-1fc1e9a15e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>option[value=lohi&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
