<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sel_sort</name>
   <tag></tag>
   <elementGuidId>7e9687ad-7417-4e1e-a7df-1867764352f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[class=product_sort_container&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
